image: docker.elastic.co/beats/filebeat-oss

daemonset:
  filebeatConfig:
    filebeat.yml: |
      filebeat.inputs:
      - type: container
        paths:
          - /var/log/containers/*.log
        processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"
      output.elasticsearch:
        host: '${NODE_NAME}'
        hosts: ["https://elasticsearch-master:9200"]
        username: '${ELASTICSEARCH_USERNAME}'
        password: '${ELASTICSEARCH_PASSWORD}'
        index: "filebeat-oss-%{[agent.version]}-%{+yyyy.MM.dd}"
        ssl.certificate_authorities:
          - /usr/share/filebeat/certs/ca.crt
      setup.ilm.enabled: false
      setup.template.name: "filebeat"
      setup.template.pattern: "filebeat-oss-*"
  secretMounts:
    - name: elasticsearch-master-certs
      secretName: elasticsearch-master-certs
      path: /usr/share/filebeat/certs
  resources:
    limits:
      # Should avoid OOM (Error 137) when running goss tests into the pod
      memory: "300Mi"
