extraEnvs:
  - name: "ELASTICSEARCH_HOSTS"
    value: "https://upgrade-master:9200"
  - name: "ELASTICSEARCH_USERNAME"
    valueFrom:
      secretKeyRef:
        name: upgrade-master-credentials
        key: username
  - name: "ELASTICSEARCH_PASSWORD"
    valueFrom:
      secretKeyRef:
        name: upgrade-master-credentials
        key: password
  - name: ssl.certificate_authorities
    value: "/usr/share/filebeat/certs/ca.crt"
filebeatConfig:
  filebeat.yml: |
    filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/*.log
      processors:
      - add_kubernetes_metadata:
          host: ${NODE_NAME}
          matchers:
          - logs_path:
              logs_path: "/var/log/containers/"
    output.elasticsearch:
      host: '${NODE_NAME}'
      hosts: '${ELASTICSEARCH_HOSTS:upgrade-master:9200}'
      username: '${ELASTICSEARCH_USERNAME}'
      password: '${ELASTICSEARCH_PASSWORD}'
      protocol: https
      ssl.certificate_authorities:
      - /usr/share/filebeat/certs/ca.crt
secretMounts:
  - name: upgrade-master-certs
    secretName: upgrade-master-certs
    path: /usr/share/filebeat/certs
resources:
  limits:
    # Should avoid OOM (Error 137) when running goss tests into the pod
    memory: "300Mi"
